INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (1, 'by', 'БЕЛАРУСЬ', 172);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (2, 'RU', 'Россия', 264);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (3, 'UA', 'Украина', 311);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (4, 'DEN', 'ДАНИЯ', 199);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (5, 'CN', 'КИТАЙ', 185);