INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (1, 'BY', 'БЕЛАРУСЬ', 172);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (2, 'UA', 'УКРАИНА', 156);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (3, 'RU', 'РОССИЯ', 264);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (4, 'US', 'США', 290);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (5, 'GB', 'ВЕЛИКОБРИТАНИЯ', 202);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (6, 'CN', 'КИТАЙ', 185);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (7, 'JP', 'ЯПОНИЯ', 222);
INSERT INTO PUBLIC.COUNTRY (ID, ABBREVIATION, NAME, CURRENCY_ID) VALUES (8, 'FR', 'ФРАНЦИЯ', 199);